### PR TITLE
update 2.501, fixes #7

### LINKED ISSUE #7: missing Hebrew glyph ר resh-hb in Bold
Condensed:
screen shot 2017-10-21 at 1 45 15 pm

Bold Condensed: 
screen shot 2017-10-21 at 1 45 09 pm

### PR DESCRIPTION
**Pull request by alexeiva**

### CODE REVIEW

**Comment by m4rc1e** [comment]
@alexeiva please give me a poke when this is give to pr to GF

**Comment by alexeiva** [comment]
@m4rc1e this is good for pushing to GF now. 
Next update with Cyrillic Pro will be in about a month.

**Comment by m4rc1e** [comment]
Can we include #5 in this?

**Comment by alexeiva** [comment]
yes, please wait

**Comment by alexeiva** [comment]
good to merge now with #5 fix

**Comment by m4rc1e** [comment]
ping @davelab6

**Comment by davelab6** [comment]
Thanks!!

**Pull request merged**
